[alipay]
appid="2016092700608220"
# 在支付宝平台的支付宝所属的公钥,不是自己生成的
alipay_rsa_public_key="MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqjGPRr3dQWOBAhKNR7hdI9VDit6DTlNcaIbed2s9+dOOpXQFDaCPiYm+I/Mr94kqbPWzEC/NtEUam/vIM7/JMTr48aGEtOxUPWFI1yJbWIQgTZg+aem1sy4ROET8Bx2bSNIluZzaoCfzQ16IZ7KDLc1Et0A/tvkpwoBUOZL6KAT74VvflL056AQx+fRc50bNKR+0enrKvYy/Jub6mhTpd66+4J/J6KyqcixnoCuXQjwZFT0Vkd2KxBdlICKI9vlPR4BwSuBMsmg8Lv/gYMHa6kKX144zEGk51qFgOv1COWzZsnTwvwgoD7CM9W0cMnn4wBuKm3Rr4fatzDi+oNGRKwIDAQAB"
# 自己生成的秘钥对里边的私钥
rsa_private_key="MIIEowIBAAKCAQEAtpeT4MukJgBDEGQoj0/GJr1VKhSu9lnL6wQ35WjOdzU8Dh0c8/VetOf52TBzlMz/VXus8UQrw2WjvyNH7M2gs5wg3/2GhHSHNJWhpuPJjAGcgcAN7OOTakga5wrhPT+/yOlTKZyCWM6MdzYku3j4+BJshuLWg86c3SdcX3DAVe7PsI7BV2iqgMu62RqwwYpdIpm3KuaCZXf1Sp4l1QaaNu479A4jq18nJAuSCWZQ3jZqTfYcLao0CS46XWe3YeN4n9FkQyQvzq6Z9UGsfqMTbAaFKuqzS3JqsPLiqY1GAfgs09xIC+cOqBz06IvvZFGxy4XX4f41iUgG9YhAqN+LHwIDAQABAoIBAAEM5Cvh4ALb84bPnLAeXFxysF+6mLsQDy096/hk3vMumjbWkgkRO0c9ImHOdou/liRuvrLwmnPYTNXXpR1GnYsK9eFz+uceKHzz82cbXlhw1e6lJS9cq8drvMPheyQ4DqlgNjtCDDnojkRNSm7Nplj++iLYgTVm5d4b0Ns3sdOMtqIbLv3PGQYubEbrfDbzNnuTAObW0WAQUa5BOja1gaOL77htGb20jRs2jQdErnDoG22QApldOVm8mb4Cp9l5maWXx/88r7a8E1uXsR/EYQm2gVfI60d3PiHtFQigj9EJ0IesM8A4O2gvNZZND466AvQDUXUJ3HtZg5hq32FIvikCgYEA8qvkIWMiIUxc2KdiB0YxtksPLY0vYNf295HZ/EiI5iZAHaPEivLYp3Q4U23hyESm2azmlR/7zgjbBoTeAE4HckHQ2oOrO/RZRihy+u7b35BcH2Pt0XAMnU9fysPO2V90jTcHKe8sG7bf+0DqIBr8ZaAug4mlN1w8kAUOCn8uzLUCgYEAwJ7vJF+BDBItYk0Lagj5+HjS30hYmSUjdNgQk4XkAMLg3Y7hltDFxyWIYrg8ErnIYKQoit+gVQ1ClIjRygCKdOuhwA8iv0fNdJ6ZPc/yHWMbFMYhgdmvaXJnqWkTAPAs/7TH7Z0U1iO/gcvcTbu0lM98W5KHfl9MAt6BI7jisQMCgYEAgtEY1Mq8/lhNANoSpTs41z1VPEgMz1b8om70pORxMChUjeXXsNPC6Vpkds0YVr5zd4qWbrNkKahqcfQ0PNPTfctvDCzIpTRO39w0R4N18em/T4iuDiYqFq9QQ10U5+dmTC3q5bcx/uqxiZ9v1sjVYO9dw7jy4IoPd8/RxuTS1LUCgYBfifVfeydMz29HRKOWsmEaBwPAz+dx/mO5vrlqEozme8KA4i+uWFrgzhL5tBvHxfJHTOT3DLg/t1YAymQT53TFTWJrGpbHfVvArjGf4RZb0R5LjYJtH4XLrX0RIBbW7knDgu1vQ+xj0lNYk77vp1yIOumZmfIukiHngmlXSIrX9QKBgEnWXZoydbsntBIg8QalzvUOTOPXwHYFNvDVa4YqtoNOep8nkCH+Y3n21N08Z9kiCScwt6qCqY3na1624tfskJM7RZb+zP2Qf4/RYsgYdpUM2xmN6Nhk0UbnP4YHICCI1kMDkFd3Pnt4A5Ec9cdGwHpD1vh/G1xau/4B7xIfUsd0"
# 异步通知的接口地址
notify_url="http://abc.com/"
# 网页支付时,充值成功之后将会跳转到这里
return_url="http://abc.com/"
# 是否是生产环境
product=false

[wechat]
appid="2016092700608220"
mch_id="12332312"
notify_url="http://abc.com/"
sign_key="123eqeqwqwe"

# 其他三方支付配置同样写这下边